config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts do
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ActiveHash::Base
  self.data = [
     {id: 1, name: '---'},
     {id: 2, name: 'アークテリクス(ARCTERYX)'},
     {id: 3, name: 'エムエスアール(MSR)'}, 
     {id: 4, name: 'コールマン(Coleman)'}, 
     {id: 5, name: 'ザ・ノース・フェイス(THE NORTH FACE)'}, 
     {id: 6, name: 'スノーピーク(SNOW PEAK)'}, 
     {id: 7, name: 'ハイパーライトマウンテンギア(HYPERLITE MOUNTAIN GEAR)'}, 
     {id: 8, name: 'パタゴニア(patagonia)'},
     {id: 9, name: 'モンベル(mont bell)'},
     {id: 10, name: '山と道'},
     {id: 11, name: 'その他'}
]

include ActiveHash::Associations
has_many :posts

end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'Tシャツ、インナー' },
    { id: 3, name: 'レインウェア' },
    { id: 4, name: 'ダウンウェア' },
    { id: 5, name: 'パンツ' },
    { id: 6, name: 'シューズ・サンダル' },
    { id: 7, name: 'バックパック' },
    { id: 8, name: '寝袋' },
    { id: 9, name: 'テント' },
    { id: 10, name: 'テーブル、イス' },
    { id: 11, name: 'ランタン' },
    { id: 12, name: '調理用品' },
    { id: 13, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :posts 

  end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :item_name, presence: true
  validates :price, presence: true
  validates_numericality_of :price, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999
  validates :price, format: { with: /\A[0-9]+\z/ }
  validates :category_id, presence: true
  validates :etc, presence: true
  validates :user, presence: true
  validates :image, presence: true

  with_options numericality: { other_than: 1, message: "を選択してください"} do
    validates :category_id
    validates :brand_id
  end
  
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  belongs_to :brand


  def was_attached?
    self.image.attached?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 

   validates :nickname, presence: true
   validates :first_name, presence: true
   validates :last_name, presence: true
   validates :first_name_kana, presence: true
   validates :last_name_kana, presence: true
   validates :birthday, presence: true

   VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  validates_format_of :password, with:  VALID_PASSWORD_REGEX, message: 'には英字と数字の両方を含めて設定してください'

  validates :first_name,:last_name, format: {with:/\A[ぁ-んァ-ヶ一-龥々ー]+\z/,message: 'を全角で入力してください'}
  validates :first_name_kana,:last_name_kana, format: {with: /\A[ァ-ヶー－]+\z/,message: 'を全角カタカナで入力してください'}
  
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :first_name, :last_name, :first_name_kana, :last_name_kana, :birthday])
  end
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.includes(:user).order("created_at DESC")
  end

  def new
    @post = Post.new
    @posts = Post.all
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
    unless current_user.id == @post.user_id 
      redirect_to action: :index
   end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    unless current_user.id == @post.user_id
      redirect_to root_path
    else
      redirect_to action: :index
    end
      @post.destroy
  end

  def search
    # params[:q]がnilではない且つ、params[:q][:name]がnilではないとき（商品名の欄が入力されているとき）
    # if params[:q] && params[:q][:name]と同じような意味合い
    if params[:q]&.dig(:item_name)
      # squishメソッドで余分なスペースを削除する
      squished_keywords = params[:q][:item_name].squish
      ## 半角スペースを区切り文字として配列を生成し、paramsに入れる
      params[:q][:item_name_cont_any] = squished_keywords.split(" ")
    end
    @q = Post.ransack(params[:q])
    @posts = @q.result
  end

  private
  def post_params
    params.require(:post).permit(:item_name, :brand_id, :category_id, :purchase_date_id, :price, :weight, :etc, :good_point, :bad_point, :cost_rationg, :function_rating, :weight_rating, :design_rationg, :recommend_rating, :image).merge(user_id: current_user.id)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def show
    @nickname = current_user.nickname
    @posts = current_user.posts
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <%= render 'layouts/error_messages', model: form.object %>
<% end %>

app/views/posts/edit.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <title>GEAR LOG</title>
  </head>
  <body>
    <header>
      <div class="heading">
      <%=link_to 'GEAR LOG', root_path, class:"title" %>
       
      </div>
      <div class="navbar">
          <ul class="nav-lists">
    <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %></li>
      <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
    </ul>
      </div>
       <% end %>
    </header>
    
  <div class="items-sell-contents">
  <header class="items-sell-header">

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">投稿編集</h2>
    <%= form_with model: @post, local: true do |f| %>

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :item_name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :etc, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（オススメポイント、イマイチポイントなど）例）防水性や防風性は高いですが、生地がやや厚めなため、夏場は少し使いにくいです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          ブランド
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:brand_id, Brand.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>商品のレーティング</span>
       
      </div>
      
      <div class="form">
            
        <div class="weight-bold-text">
          オススメ度
          <span class="indispensable">必須</span>
        </div> 

<div class="star-field">
    <input id="star5" type="radio" name="post[recommend_rating]" value="5" />
    <label for="star5">★</label>
    <input id="star4" type="radio" name="post[recommend_rating]" value="4" />
    <label for="star4">★</label>
    <input id="star3" type="radio" name="post[recommend_rating]" value="3" />
    <label for="star3">★</label>
    <input id="star2" type="radio" name="post[recommend_rating]" value="2" />
    <label for="star2">★</label>
    <input id="star1" type="radio" name="post[recommend_rating]" value="1" />
    <label for="star1">★</label>
</div>
      </div>
    </div>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>購入価格<br>(定価)</span>
        
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）16800" %>
        </div>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている投稿内容、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        また、投稿をもちまして
        <a href="#">利用規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" , class:"sell-btn" %>
      <%=link_to 'もどる', post_path(@post.id), class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
  </footer>
    <footer>
      <p>Copyright(C) Gear Log ALL RIGHTS RESERVED.</p>
    </footer>
</div>
</body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="/assets/style.css">
    <title>GEAR LOG</title>
  </head>
  <body>
    <header>
      <div class="heading">
      <%=link_to 'GEAR LOG', root_path, class:"title" %>
      <div class="explain">
      山道具とキャンプ道具のレビューサイト
      </div>
      </div>
      <div class="navbar">
          <ul class="nav-lists">
    <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %></li>
      <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
    </ul>
      </div>
       <% end %>
    </header>

 <div class="contents">
      <div class="first-view">
       <%= image_tag "434B9327-4030-4869-A098-42624319B9B7.jpg", class:"top-image" %>
       <%= image_tag "2021-Q4_BLOG-DFTW-DeYoung_3200x.webp", class:"top-image" %>
       <%= image_tag "DSC05862 2.JPG", class:"top-image" %>
       <%= image_tag "2022_04_hometop_01_01.jpeg", class:"top-image" %>
      </div>
         <div class='search-bar-contents'>

      <%= search_form_for Post.ransack(params[:q]), url: search_posts_path, html: {class: "search-form"} do |f| %>
      <%= f.text_field :item_name, placeholder: '商品名から探す', class: 'search-box-top' %>
      <%= f.label :submit, class: "search-button" do %>
        <input type="submit" value="検索" class="search-button">
        <%= f.submit :submit, id: "q_submit", style: "display: none;"%>
      <% end %>
    <% end %>
   
       <h3><%= link_to '詳細検索', search_posts_path, class:"search-link"%></h3>
 </div>
      <div class="upper-content">
        <h2 class="heading-name">新規投稿</h2>
        <ul class="messages">
          <li class="message">
           
            
          </li>
        </ul>
     <ul class='item-lists'>
        <% @posts.each do |post| %>
      <li class='list'>
        <%= link_to post_path(post.id) do %>
        <div class='item-img-content'>
          <%= image_tag post.image, class: "item-img" %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= post.item_name %>
          </h3>
          <div class='etc'>
            <span><%= post.etc %></span>
          </div>
          <div class='item-price'>
            <span><%= post.price %>円<br></span>
          </div>
          <div class='recommend-rating'>
                <div class="star">
            <% if post.recommend_rating? %>
            <% for i in 1..post.recommend_rating do %>
             ★
            <% end %>
            </div>
            <% end %>
           </div>
         </div>
        <% end %>
      </li>
      <% end %>
    </ul>
    </div>


<%= link_to(new_post_path, class: 'purchase-btn') do %>
 
  <%= image_tag 'icon_000680_256.png', size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>

<footer class="items-sell-footer">

    <footer>
      <p>Copyright(C) Gear Log ALL RIGHTS RESERVED.</p>
    </footer>
  </body>
</html>

app/views/posts/new.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="/assets/style.css">
    <title>GEAR LOG</title>
  </head>
  <body>
    <header>
      <div class="heading">
      <%=link_to 'GEAR LOG', root_path, class:"title" %>
      </div>
      <div class="navbar">
          <ul class="nav-lists">
    <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %></li>
      <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
    </ul>
      </div>
       <% end %>
    </header>
    
    
  <div class="items-sell-contents">
  <header class="items-sell-header">

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">新規投稿</h2>
    <%= form_with model: @post, local: true do |f| %>

    <%# 商品画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        商品画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /商品画像 %>
    <%# 商品名と商品説明 %>
    <div class="new-items">
      <div class="weight-bold-text">
        商品名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :item_name, class:"items-text", id:"item-name", placeholder:"商品名（必須 40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          商品の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :etc, class:"items-text", id:"item-info", placeholder:"商品の説明（必須 1,000文字まで）（オススメポイント、イマイチポイントなど）例）防水性や防風性は高いですが、生地がやや厚めなため、夏場は少し使いにくいです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
    <%# /商品名と商品説明 %>

    <%# 商品の詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">商品の詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          カテゴリー
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          ブランド
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:brand_id, Brand.all, :id, :name, {}, {class:"select-box", id:"item-sales-status"}) %>
      </div>
    </div>
    <%# /商品の詳細 %>

    <%# 配送について %>
    <div class="items-detail">
      <div class="weight-bold-text question-text">
        <span>商品のレーティング</span>
       
      </div>
      
      <div class="form">
      
        
        <div class="weight-bold-text">
          オススメ度
          <span class="indispensable">必須</span>
        </div>
       
                <div class="star-field">
    <input id="star5" type="radio" name="post[recommend_rating]" value="5" />
    <label for="star5">★</label>
    <input id="star4" type="radio" name="post[recommend_rating]" value="4" />
    <label for="star4">★</label>
    <input id="star3" type="radio" name="post[recommend_rating]" value="3" />
    <label for="star3">★</label>
    <input id="star2" type="radio" name="post[recommend_rating]" value="2" />
    <label for="star2">★</label>
    <input id="star1" type="radio" name="post[recommend_rating]" value="1" />
    <label for="star1">★</label>
</div>
      </div>
    </div>
    <%# /配送について %>

    <%# 販売価格 %>
    <div class="sell-price">
      <div class="weight-bold-text question-text">
        <span>購入価格<br>(定価)</span>
        
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"item-price", placeholder:"例）16800" %>
        </div>
      </div>
    </div>
    <%# /販売価格 %>

    <%# 注意書き %>
    <div class="caution">
      <p class="sentence">
        <a href="#">禁止されている投稿内容、</a>
        <a href="#">行為</a>
        を必ずご確認ください。
      </p>
      <p class="sentence">
        また、投稿をもちまして
        <a href="#">利用規約</a>
        に同意したことになります。
      </p>
    </div>
    <%# /注意書き %>
    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">


  </footer>
      <footer>
      <p>Copyright(C) Gear Log ALL RIGHTS RESERVED.</p>
    </footer>
</div>
</body>
</html>

app/views/posts/search.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="/assets/style.css">
    <title>GEAR LOG</title>
  </head>
  <body>
  <div class="wrap">
    <header>
      <div class="heading">
      <%=link_to 'GEAR LOG', root_path, class:"title" %>
       
      </div>
      <div class="navbar">
          <ul class="nav-lists">
    <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %></li>
      <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
    </ul>
      </div>
       <% end %>
    </header>
  <%# /商品の概要 %>
<div class="search-contents">

 <div class='middle-contents' id="detailed-search-result-wrapper">
  <%= search_form_for @q, url: search_posts_path, html: {id: "detailed-search-form"} do |f| %>
    <div class="search-field">
      <%= f.label :item_name, '商品名' %>
      <br>
      <%= f.text_field :item_name, placeholder: '商品名', value: params[:q]&.dig(:name) %>
    </div>
    <div class="search-field">
      <%= f.label :user_nickname_cont, '投稿者名' %>
      <br>
      <%= f.text_field :user_nickname_cont, placeholder: '投稿者名' %>
    </div>   
        <div class="search-field">
      <%= f.label :category_id_eq, 'カテゴリ' %>
      <br>
      <%= f.collection_select(:category_id_eq, Category.all, :id, :name, {include_blank: "---"}) %>
    </div>
      <div class="search-field">
      <%= f.label :brand_id_eq, 'ブランド' %>
      <br>
      <%= f.collection_select(:brand_id_eq, Brand.all, :id, :name, {include_blank: "---"}) %>
    </div>
        <div class="search-field">
      <%= f.label :price_gteq, '価格'%>
      <br>
      <%= f.number_field :price_gteq %> 円以上
      <br>
      <%= f.number_field :price_lteq %> 円以下
    </div>
     <%= f.submit '検索', class: "search-btn"%>
  <% end %>
     <ul class='search-item-lists'>
        <% @posts.each do |post| %>
      <li class='list'>
        <%= link_to post_path(post.id) do %>
        <div class='item-img-content'>
          <%= image_tag post.image, class: "item-img" %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= post.item_name %>
          </h3>
          <div class='etc'>
            <span><%= post.etc %></span>
          </div>
          <div class='item-price'>
            <span><%= post.price %>円<br></span>
          </div>
          <div class='recommend-rating'>
                <div class="star">
            <% if post.recommend_rating? %>
        <% for i in 1..post.recommend_rating do %>
          ★
        <% end %>
    </div>
      <% end %>
    </div>
        </div>
        <% end %>
      </li>
      <% end %>
    </ul>
 </div>
</div>
    <footer>
      <p>Copyright(C) Gear Log ALL RIGHTS RESERVED.</p>
    </footer>
    </div>
  </body>
</html>

app/views/posts/show.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <title>GEAR LOG</title>
  </head>
  <body>
    <header>
      <div class="heading">
      <%=link_to 'GEAR LOG', root_path, class:"title" %>
       
      </div>
      <div class="navbar">
          <ul class="nav-lists">
    <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %></li>
      <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
    </ul>
      </div>
       <% end %>
    </header>

  <div class="items-sell-contents">
  <header class="items-sell-header">

  </header>
    
    <%# 商品の概要 %>
<div class="post-show">
  <div class="post-box">
    <div class="post-img-content">
      <%= image_tag @post.image, class:"post-box-img" %>
    </div>
    <h2 class="name">
      <%= @post.item_name %>
    </h2>
    <div class="item-price-box">
      <span class="item-brand">
        <%= @post.brand.name %>
      </span>
      <span class="item-category">
        <%= @post.category.name %>
      </span>
      <span class="item-price">
        ¥ <%= @post.price %>
      </span>
    </div>
    <div class="item-explain-box">
      <span><%= @post.etc %></span>
    </div>
        <div class="item-explain-box">
        <th class="detail-item">投稿者</th>
      <span><%= @post.user.nickname %></span>
    </div>
    <div class='recommend-rating'>
                <div class="showstar">
            <% if @post.recommend_rating? %>
            <% for i in 1..@post.recommend_rating do %>
             ★
            <% end %>
    </div>
    <% end %>
    </div>

  </table>
  <% if user_signed_in? && current_user.id == @post.user_id %>
    <%= link_to "商品の編集", edit_post_path(@post.id), method: :get, class: "item-red-btn" %>
    <p class="or-text">or</p>
    <%= button_to "削除", post_path(@post.id), method: :delete, class:"post-destroy" %>
  <% else %>
    <%= link_to "戻る", root_path, method: :get, class:"item-red-btn"%>
    <% end %>


<footer class="items-sell-footer">

</div>
    <footer>
      <p>Copyright(C) Gear Log ALL RIGHTS RESERVED.</p>
    </footer>
</div>
</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="style.css">
    <title>GEAR LOG</title>
  </head>
  <body>
    <header>
      <div class="heading">
      <%=link_to 'GEAR LOG', root_path, class:"title" %>
      </div>
      <div class="navbar">
          <ul class="nav-lists">
    <% if user_signed_in? %>
      <li><%= link_to current_user.nickname, "#", class: "user-nickname" %></li>
      <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
    </ul>
      </div>
       <% end %>
    </header>

<div class="contents">

<div class="user-contents">
    <ul class='item-lists'>
        <% @posts.each do |post| %>
      <li class='list'>
        <%= link_to post_path(post.id) do %>
        <div class='item-img-content'>
          <%= image_tag post.image, class: "item-img" %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= post.item_name %>
          </h3>
          <div class='etc'>
            <span><%= post.etc %></span>
          </div>
          <div class='item-price'>
            <span><%= post.price %>円<br></span>
          </div>
          <div class='recommend-rating'>
            <div class="star">
            <% if post.recommend_rating? %>
        <% for i in 1..post.recommend_rating do %>
          ★
        <% end %>
    </div>
      <% end %>
    </div>
        </div>
        <% end %>
      </li>
      <% end %>
    </ul>
</div>
</div>




        <footer>
      <p>Copyright(C) Gear Log ALL RIGHTS RESERVED.</p>
    </footer>
  </body>
</html>